### ISSUE TITLE
Create successful and reproducible indexes of 20 OSS repos

### ISSUE THREAD

**Issue by shrouxm** [sourcegraph/lsif-clang#12]
Steps for everyone:

1. Find a popular open source C++ repository which is not already documented in this thread. if you can think of one yourself, do that! otherwise here's some lists: [GitHub trending](https://github.com/trending/c++), [CodeTriage](https://www.codetriage.com/?language=C%2B%2B), [awesome-cpp](https://github.com/fffaraz/awesome-cpp).
1. Follow the documentation on this repo to create an lsif index of the chosen repository. For now, use the [simplify-cmake](https://github.com/sourcegraph/lsif-clang/tree/simplify-cmake) branch. If you're unable to create an index, file a bug documenting what you tried.
1. Follow the sourcegraph documentation to upload the lsif index to sourcegraph.com, and confirm that the c++ codenav works (feel free to spend lots of time here, C++ is a strange beast so click on some strange code to make sure it's getting indexed properly!)
1. Document the steps from cloning to successful index creation (not including getting deps for and building lsif-clang)

Steps for Garo:

1. Reproduce all of the above

**Comment by efritz** [comment]
My findings:

## bottlerocket-os/bottlerocket

In progress

## google/flatbuffers

In progress

## grpc/grpc

In progress

## nlohmann/json

In progress

## protocolbuffers/protobuf

In progress

## microsoft/terminal

In progress

**Comment by gbrik** [comment]
## FFmpeg/FFmpeg
- Language: C
- Environment: Ubuntu 20.04
- Steps:
```bash
./configure
bear make
<unmodified lsif-clang invocation>
```

**Comment by gbrik** [comment]
## nlohmann/json
- Language: C++
- Environment: Ubuntu 20.04
- Steps:
```bash
cmake -B build -S . -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
ln -s $(pwd)/build/compile_commmands.json ./
<unmodified lsif-clang invocation>
```

**Comment by gbrik** [comment]
## tensorflow/tensorflow
- Language: C++
- Environment: Ubuntu 20.04
- Steps:
  - follow https://www.tensorflow.org/install/source to get deps
  -
```
./configure
bear -o compile_commands_raw.json bazel build //tensorflow/tools/pip_package:build_pip_package
jq '[ .[] | select(.file | startswith("tensorflow")) ]' compile_commands_raw.json | grep -v -e '-fno-canonical-system-headers' > compile_commands.json
<unmodified lsif-clang invocation>
```

**Comment by gbrik** [comment]
## torvalds/linux
- Language: C++
- Environment: Ubuntu 20.04
- Steps:
  - use the table in Documentation/process/changes.rst to install deps
  -
```
make allyesconfig
make CC=clang-10 HOSTCC=clang-10
scripts/gen_compile_commands.py
<unmodified lsif-clang invocation>
```

**Comment by gbrik** [comment]
## envoyproxy/envoy
- Language: C++
- Environment: Ubuntu 20.04
- Steps:
```
./bazel/setup_clang.sh /usr/lib/llvm-10    `# or wherever your llvm installation lives`
echo 'build --config=clang' > user.bazelrc
TEST_TMPDIR=/tmp tools/gen_compilation_database.py --include_headers --run_bazel_build
<unmodified lsif-clang invocation>
```

**Comment by gbrik** [comment]
## grpc/grpc
- Language: C++
- Environment: Ubuntu 20.04
- Steps:
```
cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -Dgrpc_BUILD_TESTS=ON -G Ninja
ninja -C build $(grep -e 'build gens' build/build.ninja | awk '{print $2}')  `# generate pb`
lsif-clang build/compile_commands.json
```

**Comment by gbrik** [comment]
## falcosecurity/falco
- Language: C++/C
- Environment: Ubuntu 20.04
- Steps:
```sh
sudo apt install git cmake build-essential libncurses-dev pkg-config autoconf libtool libelf-dev -y
sudo apt install libssl-dev libc-ares-dev libprotobuf-dev protobuf-compiler libjq-dev libgrpc++-dev protobuf-compiler-grpc libcurl4-openssl-dev
cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G Ninja
ninja -C build $(egrep -e '^build[^:]+.pb.(cc|h|c|cpp)[: ]' build/build.ninja)
lsif-clang build/compile_commands.json
```

**Comment by macraig** [comment]
### prabhuomkar/pytorch-cpp

- Language: C++
- Environment: macOS 10.15
- Steps: 
```
cmake -B build -DPATH_TO_LLVM=/usr/local/opt/lib
make -j8
../lsif-clang/build/bin/lsif-clang --project-root=$(pwd) --executor=all-TUs compile_commands.json --extra-arg="-resource-dir=$(clang -print-resource-dir)" > dump.lsif
