### ISSUE TITLE
definitions aren't output for templates

### ISSUE THREAD

**Issue by gbrik** [sourcegraph/lsif-clang#14]
For example, see https://sourcegraph.com/github.com/envoyproxy/envoy@670a4a6/-/blob/source/common/common/cleanup.h#L30:26

![image](https://user-images.githubusercontent.com/3411715/94837855-c5be3000-03e2-11eb-8bb2-72a0fdfeb8e0.png)

hover and references are all computed correctly, but no definition vertex is output.

https://sourcegraph.com/github.com/envoyproxy/envoy@670a4a6/-/blob/source/common/http/conn_manager_impl.cc#L127:31 is another good example, it even correctly infers the type of the `auto` variable, just the j2d is missing.

**Comment by aidaeology** [comment]
@gbrik What is the status of this issue, was this resolved with the 3.20 milestone or does it still need work? If it's resolved and longer a problem then please mark as closed and link the relevant PR. Otherwise please provide a status update on what the remaining work is to get it resolved.
