### ISSUE TITLE
Support newer version of clang?

### ISSUE THREAD

**Issue by bhush9** [sourcegraph/lsif-clang#62]
Hello!

Is there any plan to add support for newer version of clang? In some distributions only packages for newer clang are available and that makes it hard to build this.

Thanks.

**Comment by varungandhi-src** [comment]
Could you expand on what the issue is (e.g. which distro, which Clang version, what the build error is)? Normally, Clang releases are largely backwards compatible, and the code here should not be using the libclang that is installed through the OS package manager.

**Comment by jlisee** [comment]
In an effort to get a more stable version of the tool [jlisee/llvm-13.0.1-upgrade-v2](https://github.com/jlisee/lsif-clang/tree/jlisee/llvm-13.0.1-upgrade-v2).  The main changes are in this commit jlisee/lsif-clang@df04f9e0d0bac389ea83fea309dc56c8fcb152dd, GitHub is not smart enough to only show merge changes but it just maintained to 2 small changes to the `clangd` source).


----

In the build above with Clang 13 and one issue I found is that CMakeLists don't specify which exact version of LLVM should be used.  The are not always compatible and fixing the version is way to make sure the build works.
