### ISSUE TITLE
Check stack traces and use backward-cpp if it isn't working

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/lsif-clang#73]
A customer reported that they didn't get a stack trace on a segfault, I thought we already had code which handled this. We should manually test if this works and set up https://github.com/bombela/backward-cpp if it isn't working.

**Comment by Strum355** [comment]
Looks like backward-cpp got removed when this repo got shuffled around into being a "fork". Heres the old PR from when it was introduced https://github.com/sourcegraph/lsif-clang/pull/32. 

Of note, it didn't seem to work in all situations for reasons beyond my capability to explore, specifically I believe if it segfaulted in one of the worker threads it would not work
